apiVersion: v1
kind: Service
metadata:
  name: eusuite-login
  namespace: eucloud
  labels:
    app: eusuite-login
spec:
  type: NodePort
  selector:
    app: eusuite-login
  ports:
  - name: http
    port: 80
    targetPort: 80
    nodePort: 30090
    protocol: TCP
  sessionAffinity: None
